#!/usr/bin/env bash

set -euo pipefail
set -x

name=
version=

while test $# -gt 0; do
  case $1 in
    --name)
      name=$2
      shift
      ;;
    --version)
      version=$2
      shift
      ;;
    *)
      echo >&2 "Invalid argument: $1"
      exit 1
      ;;
  esac
  shift
done

if [[ "${name}" == "" || "${version}" == "" ]]; then
  echo "Name and version"
  exit 1
fi

"/run-test" "${version}"