api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate Apache HTTPD server"
  homepage = "https://github.com/paketo-buildpacks/httpd"
  id = "paketo-buildpacks/httpd"
  keywords = ["apache", "httpd", "server", "distribution"]
  name = "Paketo Buildpack for Apache HTTP Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:apache:http_server:2.4.53:*:*:*:*:*:*:*"
    id = "httpd"
    licenses = ["Apache-2.0", "BSD-3-Clause", "Beerware", "ECL-2.0", "RSA-MD", "SHL-0.5", "SHL-0.51", "Spencer-94"]
    name = "Apache HTTP Server"
    purl = "pkg:generic/httpd@2.4.53?checksum=d0bbd1121a57b5f2a6ff92d7b96f8050c5a45d3f14db118f64979d525858db63&download_url=http://archive.apache.org/dist/httpd/httpd-2.4.53.tar.bz2"
    sha256 = "351bd6f0a28c013ab6b17993cc96fb6a3a2fb87bca8ed2477a1c32efec95cb7f"
    source = "http://archive.apache.org/dist/httpd/httpd-2.4.53.tar.bz2"
    source_sha256 = "d0bbd1121a57b5f2a6ff92d7b96f8050c5a45d3f14db118f64979d525858db63"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/httpd/httpd_2.4.53_linux_x64_bionic_351bd6f0.tgz"
    version = "2.4.53"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "httpd"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
  mixins = ["libexpat1"]
