
[buildpack]
id = "org.cloudfoundry.buildpacks.httpd"
name = "Apache HTTP Server Buildpack"
version = "0.0.1"

[[metadata.dependencies]]
id = "httpd"
name = "Apache HTTP Server"
sha256 = "0bc0a2a8734dcfdb699379d4cc25f33397107f868b45905bdb0f97aa3ae98855"
stacks = ["org.cloudfoundry.stacks.cflinuxfs2"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.38-linux-x64-cflinuxfs2-0bc0a2a8.tgz"
version = "2.4.38"

[[metadata.dependencies]]
id = "httpd"
name = "Apache HTTP Server"
sha256 = "97dc78de69c5615e1d2c69cd847256c38611209c479c87bfaa7510b3b45e6ccc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/httpd/httpd-2.4.38-linux-x64-cflinuxfs3-97dc78de.tgz"
version = "2.4.38"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs2"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
