name: 'Compile HTTPD on Target'
description: |
  Compiles HTTPD given a version, output directory, and a target image to compile on
on:
  push:
    branches:
      - 'main'

inputs:
  version:
    description: 'dependency version'
    required: true
  outputDir:
    description: 'output directory'
    required: true
  target:
    description: 'dependency OS target variant'
    required: true

runs:
  using: 'composite'
  steps:

  - name: docker build
    id: docker-build
    shell: bash
    run: docker build -t compilation -f dependency/actions/compile/${{ inputs.target }}.Dockerfile dependency/actions/compile

  - name: docker run
    id: docker-run
    shell: bash
    run: docker run -v ${{ inputs.outputDir }}:/home compilation --version ${{ inputs.version }} --outputDir /home --target ${{ inputs.target }}

  - name: print contents of output dir
    shell: bash
    run: ls -lah ${{ inputs.outputDir }}

  - name: prepare test
    id: prepare-test
    shell: bash
    run: docker build -t test -f dependency/test/${{ inputs.target }}/Dockerfile dependency/test/${{ inputs.target }}

  - name: run test
    id: run-test
    shell: bash
    run: docker run -v ${{ inputs.outputDir }}:/tarball_path test --version ${{ inputs.version }}
